spring.application.name=base
server.port=${PORT:8182}
server.color = orange

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.table=sf_course_flyway_schema_history
spring.flyway.baseline-version=0